Forward AutodIff Compatibility
JuliaSpace/SatelliteToolboxGravityModels.jl pull request #3
Opened 2024-09-25 00:07 UTC by jmurphy6895

I changed the internal time to be handled as seconds past JD_J2000 instead of DateTime to allow for automatic differentiation compatibility and changed some of the return types to handle more general inputs, namely ForwardDiff's Duals. Reverse Autodiff is blocked by not knowing how to handle the DCM struct at the moment but will be handled in a future PR.

The previous DateTime interfaces are still present they just internally convert the DateTime to the seconds past JD_J2000 and call the newer function.

2024-09-25 12:31 UTC, ronisbr commented
Hi @jmurphy6895 !

Aweome PR, thank you very much! I just added some general comments, check, please, if they apply.

2024-09-25 14:24 UTC, ronisbr commented
Hi @jmurphy6895,

Can you please check if the failures are only related to test packages that cannot be installed in Julia 1.6? If so, can you modify the test script to ignore those tests in Julia 1.6? I plan to drop support for Julia 1.6 but it will take sometime to update all packages in SatelliteToolbox.jl ecosystem.

2024-09-25 16:24 UTC, jmurphy6895 commented
Hey @ronisbr,

I don't see your comments on the PR, are they on a different branch or maybe not pushed?

As for the failure, yeah it looks like it's because of Julia 1.6:
`LoadError: Unsatisfiable requirements detected for package FiniteDiff`
...
`restricted by julia compatibility requirements to versions: 2.0.0-2.22.0 or uninstalled — no versions left`

I added a conditional to not run on v1.6

2024-09-25 16:27 UTC, ronisbr requested changes

2024-09-25 16:27 UTC, ronisbr commented on src/GravityModels/accelerations.jl
> +    time::W = -43200.0;
If the parameter `W` is not used within the function, I think it is better to drop it and just use `time::Number`. AFAIR, this suggestion is written in BlueStyle or Julia documentation for coding guidelines.

2024-09-25 16:27 UTC, ronisbr commented on src/GravityModels/accelerations.jl
> +    time_JD = (datetime2julian(time) - JD_J2000) * 86400.0
Will it have an impact if we try to keep all the constants as `Integer` if possible? For example, use `86400` instead of `86400.0` and `-43200` instead of `-43200.0`. AFAIR, this approach is also mentioned somewhere in Julia documentation.

2024-09-25 16:27 UTC, ronisbr commented on src/GravityModels/accelerations.jl
> +    time::W = -43200.0;
Same comment for unnecessary type parameters.

2024-09-25 16:27 UTC, ronisbr commented
Thanks @jmurphy6895 ! I forgot to push the comments :)

2024-09-25 16:29 UTC, jmurphy6895 commented
I see why it's still failing, it's not the test it's the .toml compat, I'll loosen it and see if the tests still pass

2024-09-25 16:30 UTC, jmurphy6895 commented
I'll get to these changes after work today

2024-09-26 04:14 UTC, jmurphy6895 commented on src/GravityModels/accelerations.jl
> +    time::W = -43200.0;
Sounds good, removed

2024-09-26 04:14 UTC, jmurphy6895 commented on src/GravityModels/accelerations.jl
> +    time_JD = (datetime2julian(time) - JD_J2000) * 86400.0
Doesn't look like it I've changed this to ints around the PR

2024-09-26 04:15 UTC, jmurphy6895 commented on src/GravityModels/accelerations.jl
> +    time::W = -43200.0;
Removed

2024-09-26 04:20 UTC, jmurphy6895 commented
W.r.t. to the failing CI, it looks like the DifferentiationInterface will not work with Julia 1.6 for FiniteDIff (Julia 1.6 requires <=v2.22 and DifferentiationInterface requires >=2.23) 
![Screenshot 2024-09-25 221841](https://github.com/user-attachments/assets/e45ad1db-0c7c-4a1f-b484-7716dcf9fc36)

I don't explicitly need the DifferentiationInterface package to test this, it will just make testing all the different AD backends very easy in the future. I'll defer to you on what you'd like to happen here

2024-09-26 12:48 UTC, ronisbr commented
Hi @jmurphy6895 !

Let's ignore those errors. As soon as we merge this commit, I turn off the tests for Julia 1.6. The last thing (sorry, I missed it before): can you please return the version to 0.1.5? I prefer to have a separate commit with the version bump. After that, I will merge this PR and tag the new release :)

2024-09-26 13:22 UTC, jmurphy6895 commented
@ronisbr Done!

2024-09-26 13:23 UTC, ronisbr commented
Awesome! Let's the CI run and I will merge this! Thank you very much for the PR @jmurphy6895 !

2024-09-26 13:52 UTC, merged

2024-09-26 16:21 UTC, ronisbr commented
Hi @jmurphy6895 !

I did some modifications:

1. Fixed precompilation warnings.
2. Improved docstrings (making them less verbose).
3. Most important: fixed J2000.0 epoch definition. Your PR revealed a long-lasting bug between the code and the documentation. When we pass no time information, we fallback to J2000.0 epoch, which is 2000-01-01T12:00:00 instead of 2000-01-01T00:00:00. Hence, I modified everything to provide the coefficients at the correct definition of J2000.0 epoch.

2024-09-26 16:21 UTC, ronisbr commented
Can you please test if I broke something related to autodiff? If not, I will tag the new release.

2024-09-26 17:18 UTC, jmurphy6895 commented
LGTM, one step closer to a fully differentiable propagator!